name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Create config.js with Node.js
        run: |
          node -e "
            const fs = require('fs');
            const template = fs.readFileSync('config.js.template', 'utf8');
            
            const config = template
              .replace(/##FIREBASE_API_KEY##/g, process.env.FIREBASE_API_KEY)
              .replace(/##FIREBASE_AUTH_DOMAIN##/g, process.env.FIREBASE_AUTH_DOMAIN)
              .replace(/##FIREBASE_PROJECT_ID##/g, process.env.FIREBASE_PROJECT_ID)
              .replace(/##FIREBASE_STORAGE_BUCKET##/g, process.env.FIREBASE_STORAGE_BUCKET)
              .replace(/##FIREBASE_MESSAGING_SENDER_ID##/g, process.env.FIREBASE_MESSAGING_SENDER_ID)
              .replace(/##FIREBASE_APP_ID##/g, process.env.FIREBASE_APP_ID)
              .replace(/##POWER_BI_URL##/g, process.env.POWER_BI_URL);
            
            fs.writeFileSync('config.js', config);
            
            // Print a safe version of the config (hiding API key)
            console.log('Config created successfully');
            const configObj = JSON.parse('{' + config.split('{')[1].split('}')[0] + '}');
            configObj.firebase.apiKey = '[HIDDEN]';
            console.log(JSON.stringify(configObj, null, 2));
          "
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          POWER_BI_URL: ${{ secrets.POWER_BI_URL }}
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
