name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create config.js from template
        run: |
          cp config.js.template config.js
          
          # Replace placeholders with actual secrets
          sed -i 's/##FIREBASE_API_KEY##/${{ secrets.FIREBASE_API_KEY }}/g' config.js
          sed -i 's/##FIREBASE_AUTH_DOMAIN##/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' config.js
          sed -i 's/##FIREBASE_PROJECT_ID##/${{ secrets.FIREBASE_PROJECT_ID }}/g' config.js
          sed -i 's/##FIREBASE_STORAGE_BUCKET##/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' config.js
          sed -i 's/##FIREBASE_MESSAGING_SENDER_ID##/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' config.js
          sed -i 's/##FIREBASE_APP_ID##/${{ secrets.FIREBASE_APP_ID }}/g' config.js
          sed -i 's/##POWER_BI_URL##/${{ secrets.POWER_BI_URL }}/g' config.js
          
          # Verify config file was created
          echo "Config file created:"
          cat config.js | grep -v apiKey
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
