name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create direct config.js file
        run: |
          echo 'const config = {' > config.js
          echo '    powerBiUrl: "${{ secrets.POWER_BI_URL }}",'' >> config.js
          echo '    firebase: {' >> config.js
          echo '        apiKey: "${{ secrets.FIREBASE_API_KEY }}",'' >> config.js
          echo '        authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",'' >> config.js
          echo '        projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",'' >> config.js
          echo '        storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",'' >> config.js
          echo '        messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",'' >> config.js
          echo '        appId: "${{ secrets.FIREBASE_APP_ID }}"'' >> config.js
          echo '    }' >> config.js
          echo '};' >> config.js
          
          # Check if config.js was created successfully
          echo "Checking config.js was created:"
          ls -la config.js
          
          # Verify file size (without showing sensitive content)
          echo "File size: $(wc -c < config.js) bytes"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
