name: Deploy Web App
on:
  push:
    branches: [ main ]  # Adjust branch name if needed

permissions:
  contents: write # This is important for GitHub Pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate config.js with secrets
        run: |
          cat > config.js << 'EOF'
          const config = {
            powerBiUrl: "${{ secrets.POWER_BI_URL }}",
            firebase: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}"
            }
          };
          EOF
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Deploy entire repository content
          branch: gh-pages # The branch the action should deploy to
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates this secret
