name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate index.html with secrets
        run: |
          # Read the template index.html file
          template=$(cat index-template.html)
          
          # Replace placeholders with actual values - NO QUOTES around variables
          # This is the key fix - using environment variables directly without quotes
          result=${template//FIREBASE_API_KEY/$FIREBASE_API_KEY}
          result=${result//FIREBASE_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN}
          result=${result//FIREBASE_PROJECT_ID/$FIREBASE_PROJECT_ID}
          result=${result//FIREBASE_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET}
          result=${result//FIREBASE_MESSAGING_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID}
          result=${result//FIREBASE_APP_ID/$FIREBASE_APP_ID}
          result=${result//POWER_BI_URL/$POWER_BI_URL}
          
          # Write the result to index.html
          echo "$result" > index.html
          
          # Verify file was created (without exposing content)
          echo "Generated index.html ($(wc -c < index.html) bytes)"
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          POWER_BI_URL: ${{ secrets.POWER_BI_URL }}
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
