name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm init -y
          npm install dotenv

      - name: Create and Run Build Script
        run: |
          cat > build.js << 'EOL'
          const fs = require('fs');
          const path = require('path');
          
          // Створюємо dist директорію
          if (!fs.existsSync('dist')) {
              fs.mkdirSync('dist');
          }
          
          // Читаємо значення змінних середовища
          const powerBiUrl = process.env.POWER_BI_URL || process.env.POWERBI_URL || "PLACEHOLDER_POWERBI_URL";
          const firebaseApiKey = process.env.FIREBASE_API_KEY || "PLACEHOLDER_FIREBASE_API_KEY";
          const firebaseAuthDomain = process.env.FIREBASE_AUTH_DOMAIN || "PLACEHOLDER_FIREBASE_AUTH_DOMAIN";
          const firebaseProjectId = process.env.FIREBASE_PROJECT_ID || "PLACEHOLDER_FIREBASE_PROJECT_ID";
          const firebaseStorageBucket = process.env.FIREBASE_STORAGE_BUCKET || "PLACEHOLDER_FIREBASE_STORAGE_BUCKET";
          const firebaseMessagingSenderId = process.env.FIREBASE_MESSAGING_SENDER_ID || "PLACEHOLDER_FIREBASE_MESSAGING_SENDER_ID";
          const firebaseAppId = process.env.FIREBASE_APP_ID || "PLACEHOLDER_FIREBASE_APP_ID";
          
          console.log('Environment variables loaded:');
          console.log('Power BI URL:', powerBiUrl.substring(0, 10) + '...');
          console.log('Firebase API Key:', firebaseApiKey.substring(0, 5) + '...');
          
          // Зчитуємо вміст HTML-файлу
          let indexContent = fs.readFileSync('index.html', 'utf8');
          
          // Створюємо конфіг
          const configScript = `<script>
          const config = {
              powerBiUrl: "${powerBiUrl}",
              firebase: {
                  apiKey: "${firebaseApiKey}",
                  authDomain: "${firebaseAuthDomain}",
                  projectId: "${firebaseProjectId}",
                  storageBucket: "${firebaseStorageBucket}",
                  messagingSenderId: "${firebaseMessagingSenderId}",
                  appId: "${firebaseAppId}"
              }
          };
          console.log("Config loaded with actual values");
          </script>`;
          
          // Замінюємо блок конфігурації
          if (indexContent.includes('<script src="config.js"></script>')) {
              // Замінюємо посилання на config.js
              indexContent = indexContent.replace('<script src="config.js"></script>', configScript);
              console.log("Replaced config.js script tag");
          } else {
              // Шукаємо інлайн конфігурацію
              const configStartTag = '<script>\n   // This will be replaced with actual values during build';
              const configEndTag = '</script>';
              
              if (indexContent.includes(configStartTag)) {
                  // Знаходимо весь блок конфігурації
                  const startPos = indexContent.indexOf(configStartTag);
                  if (startPos !== -1) {
                      const endPos = indexContent.indexOf(configEndTag, startPos) + configEndTag.length;
                      const configBlock = indexContent.substring(startPos, endPos);
                      
                      // Замінюємо весь блок
                      indexContent = indexContent.replace(configBlock, configScript);
                      console.log("Replaced inline config block");
                  }
              } else {
                  // Додаємо перед закриттям head
                  indexContent = indexContent.replace('</head>', configScript + '\n</head>');
                  console.log("Added config script before </head>");
              }
          }
          
          // Записуємо змінений HTML у папку dist
          fs.writeFileSync(path.join('dist', 'index.html'), indexContent);
          console.log("HTML file saved to dist folder");
          
          // Копіюємо інші необхідні файли
          const filesToCopy = [
            'icon.png', 
            'background.png', 
            'mayoly icon.png'
          ];
          
          for (const file of filesToCopy) {
            try {
              if (fs.existsSync(file)) {
                fs.copyFileSync(file, path.join('dist', file));
                console.log(`Copied: ${file}`);
              } else {
                console.log(`File not found, skipping: ${file}`);
              }
            } catch (err) {
              console.error(`Error copying ${file}:`, err);
            }
          }
          
          // Копіюємо CNAME файл
          if (fs.existsSync('CNAME.txt')) {
            fs.writeFileSync(path.join('dist', 'CNAME'), fs.readFileSync('CNAME.txt', 'utf8'));
            console.log("CNAME copied from CNAME.txt");
          } else if (fs.existsSync('CNAME')) {
            fs.copyFileSync('CNAME', path.join('dist', 'CNAME'));
            console.log("CNAME file copied");
          }
          
          console.log("Build completed!");
          EOL
          
          node build.js
        env:
          POWER_BI_URL: ${{ secrets.POWER_BI_URL }}
          POWERBI_URL: ${{ secrets.POWERBI_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
